---
title: "Untitled"
author: "Mohammed"
date: "2/26/2020"
output: html_document
---




```{r }
library(OpenImageR)
library("jpeg")

#image = readImage("mandrill.jpg")
#plot(image)

library("jpeg")
jj <- readJPEG("mandrill.jpg")
plot(0:1,0:1,type="n",ann=FALSE,axes=FALSE)
rasterImage(jj,0,0,1,1)
```


```{r }
reduce_dimensions <- function(input_file,width,height) { 
  img <- readJPEG(input_file)
  
  nrows = nrow(img);
  ncols = ncol(img);

  rem_rows = (nrows - width)%% 2
  rem_cols = (ncols - height)%% 2



  #remov_rows = (trunc((nrows - width)/2) + 1):(nrows - trunc((nrows - width)/2) - rem_rows)
  
    if((width %% 2) == 0) {
    remov_rows = ((nrows/2) - ( width/2)+1): ((nrows/2) + ( width/2))
    
    } else {
    remov_rows = trunc(((nrows/2) - ( width/2)+1)): trunc(((nrows/2) +( width/2)))
    }
  

  #remov_cols = (trunc((ncols - height)/2) + 1):(ncols - trunc((ncols - height)/2) - rem_cols)
    
    if((height %% 2) == 0) {
    remov_cols = ((ncols/2) - (height/2)+1): ((ncols/2) + (height/2))
    
    } else {
    remov_cols = trunc(((ncols/2)) - (height/2)+1): trunc(((ncols/2)) + (height/2))
    }
  

    
  
  new_img = array(dim = c(width, height, dim(img)[3]))
  
  for (i in 1:dim(img)[3]) {
  new_img[,, i] = img[,, i][remov_rows, remov_cols]
  }

  return(new_img)

}
dim(reduce_dimensions("mandrill.jpg", 295, 291))
```

```{r}

new_img = reduce_dimensions("mandrill.jpg", 110, 201)
plot(0:1,0:1,type="n",ann=FALSE,axes=FALSE)
rasterImage(new_img,0,0,1,1)

```


```{r}
img <- readJPEG("mandrill.jpg")

width = 295
height = 295

nrows = nrow(img);
ncols = ncol(img);

rem_rows = (nrows - width)%% 2
rem_cols = (ncols - height)%% 2



trunc(((nrows/2) +( width/2)))
```

